name: Debian packaging

on:
  push:
      branches:
        - master
        - ci_deb
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: sudo apt install curl python3 python3-build python3-wheel build-essential devscripts debhelper
    - name: Get
      uses: actions/checkout@v3
    - name: Archive
      run: |
        SRC_DIR=$(pwd)
        cd ../
        tar -cvJf slacky-manager_0.3.orig.tar.xz $SRC_DIR
        cd $SRC_DIR
    - name: Build
      run: debuild -us -uc
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: slacky_manager.deb
        path: ../slacky-manager_0.3-1_all.deb
